application: seasistaweb
version: 1
runtime: go
api_version: go1

handlers:
- url: /stylesheets
  static_dir: stylesheets
  
- url: /javascripts
  static_dir: javascripts

- url: /(.*\.(gif|png|jpg))
  static_files: images/\1
  upload: images/(.*\.(gif|png|jpg))
  
- url: /.*
  script: _go_app